"""Initial Migration

Revision ID: 3291f6873aee
Revises: b124b7560f17
Create Date: 2022-05-19 14:55:13.486316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3291f6873aee'
down_revision = 'b124b7560f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'date')
    op.add_column('wtask', sa.Column('category', sa.Text(), nullable=True))
    op.drop_column('wtask', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wtask', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('wtask', 'category')
    op.add_column('task', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
